# Generated by Django 4.1 on 2022-09-30 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseTrait',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('pubmedid', models.IntegerField(primary_key=True, serialize=False)),
                ('journal', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('URL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SNP',
            fields=[
                ('rsid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('snp_id_current', models.IntegerField()),
                ('chrom', models.CharField(max_length=2)),
                ('chrom_pos', models.IntegerField()),
                ('chrom_region', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SNPToDiseaseToReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvalue', models.IntegerField()),
                ('pvalueMLog', models.IntegerField()),
                ('ReportedGenes', models.CharField(max_length=200)),
                ('diseaseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpProjectDB.diseasetrait')),
                ('pubmedid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpProjectDB.reference')),
                ('rsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snpProjectDB.snp')),
            ],
        ),
    ]
